name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Install dependencies
      run: npm install -g npm
    - name: Initialize 
      run: npm init -y
    - name: Install playwright browsers
      run: npm install codeceptjs playwright --save-dev --legacy-peer-deps
    - name: Install allure commandline reports
      run: npm install -g allure-commandline --save-dev
    - name: Install UI
      run: npm i @codeceptjs/ui --save --legacy-peer-deps
    - uses: microsoft/playwright-github-action@v1
    - name: run CodeceptJS tests
      uses: actions/setup-node@v3  
    - name: Run Copecept tests
      run: npm run codeceptjs
